# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process..

# Site settings
title: NSS Cohort 11
description: > # this means to ignore newlines until "baseurl:"
  A class website for Nashville Software School Cohort 11 graduates. This site is where we show off our work!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nss-cohort-11.github.io/" # the base hostname & protocol for your site
github_username: NSS-Cohort-11
permalink: /:title

# Build settings
markdown: kramdown

sass:
    style: compressed
